### ISSUE TITLE
Game crashes when trying to open *.wa2 files

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WASharpIssues#11]
If you put a *.wa2 file into the Downloads Inbox folder and open the game, it will crash with the following error:

```
[ERROR]: An Unexpected Error Occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at WAPlayer.Player.CheckForOldCompiledLevels(Boolean silent) in D:\Projects\washarp\WAPlayer\Player.cs:line 2575
   at WAPlayer.Player.Start() in D:\Projects\washarp\WAPlayer\Player.cs:line 405
   at WAPlayer.MainScript.Start() in D:\Projects\washarp\WAPlayer\MainScript.cs:line 37
```

**Comment by Aryan807** [comment]
You're late to report, this bug was already discovered by me and fixed four days ago. ;)
