### ISSUE TITLE
Custom Tags are broken and crash the game

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WASharpIssues#3]
1. Archive an adventure with a custom tag.
2. Go to Sort Adventures>Sort by Tags and click on the new tag you created. This will make the tag disappear from the list, and the game doesn't return to the selection menu with the tag filter applied.
3. Exit to the main menu and then reopen the adventure selection menu. This will make the game crash with the error posted below, and it will continue crashing even after restarting the game unless you delete Current.tags.

> [ERROR]: An Unexpected Error Occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at WAPlayer.Menu.Menu.CheckCustomTagProgress() in D:\Projects\washarp\WAPlayer\Menu\Menu.cs:line 1086
   at WAPlayer.Menu.Gui.GuiCustomSelectMenu.OnInit() in D:\Projects\washarp\WAPlayer\Menu\Gui\GuiCustomSelectMenu.cs:line 80
   at WAPlayer.Menu.Gui.GuiCustomSelectMenu.Init() in D:\Projects\washarp\WAPlayer\Menu\Gui\GuiCustomSelectMenu.cs:line 22
   at WAPlayer.Menu.MenuManager.SetContent(GuiBase content) in D:\Projects\washarp\WAPlayer\Menu\MenuManager.cs:line 21
   at WAPlayer.Menu.Gui.GuiMainMenu.OnClick(Int32 currentMenuLine) in D:\Projects\washarp\WAPlayer\Menu\Gui\GuiMainMenu.cs:line 279
   at WAPlayer.Menu.Gui.GuiBase.Update() in D:\Projects\washarp\WAPlayer\Menu\Gui\GuiBase.cs:line 88
   at WAPlayer.Menu.MenuManager.Update() in D:\Projects\washarp\WAPlayer\Menu\MenuManager.cs:line 32
   at WAPlayer.Player.Start() in D:\Projects\washarp\WAPlayer\Player.cs:line 822
   at WAPlayer.MainScript.Start() in D:\Projects\washarp\WAPlayer\MainScript.cs:line 37

**Comment by Aryan807** [comment]
This bug will be fixed lately, I would suggest users not to use custom tags for now as the code needs major revamps.

**Comment by jdl96** [comment]
Just also wanted to mention that the "ding" menu sound that plays when clicking "Sort By Tags/Sort By Creators" is a little louder than normal. I'm guessing it's playing it more than once on the same frame and the stacking effect is making it louder.
